### ISSUE TITLE
Bug with launcher update

### ISSUE THREAD

**Issue by antotor** [gustavokei/electron-game-updater#4]
Hello my friend! Im glad to use you perfect launcher. But after last update - function launcher update has been broken. After download new launcher and create .bat file - launcher trigger error message and .bat file can't execute.

If you can help me - im been happy!
![img-2024-03-12-12-57-51](https://github.com/gustavokei/electron-game-updater/assets/5446923/06098bb2-27cb-47cf-9886-4d76188ced88)

**Comment by gustavokei** [comment]
Hi, thanks for the heads up!

Since your launcher is named "GWlauncher.exe" and the code is looking for both "launcher.exe" and "launcher-new.exe", this might be the issue.
https://github.com/gustavokei/electron-game-updater/blob/main/src/renderer/patcher.js#L75
```batch
      const batchContent = `
      @echo off
      set MAX_RETRIES=3
      set RETRY_COUNT=0
      
      :RETRY
      move /Y "${filePath}\\launcher-new.exe" "${filePath}\\launcher.exe"
      if errorlevel 1 (
          set /A RETRY_COUNT+=1
          if %RETRY_COUNT% lss %MAX_RETRIES% (
              timeout /t 1 /nobreak >nul
              goto RETRY
          ) else (
              echo Maximum retries reached. Exiting.
              exit /b 1
          )
      )
      start "" "${filePath}\\launcher.exe"
      del /F "${filePath}\\launcher-update.bat"
      `;
```

Have you tried replacing "launcher.exe" with "GWlauncher.exe" and "launcher-new.exe" with "GWlauncher-new.exe" in the file above? You can also try doing the opposite: using "launcher.exe" as the name of your launcher.

Finally, if possible could you also post the contents of your "launcher-update.bat"?

Thanks again!

**Comment by antotor** [comment]
Hello and thank you for reply! After change name of my launcher, i modify all code parts. 

`const replaceExecutable = () => {
      const batchContent = `
      @echo off
      set MAX_RETRIES=3
      set RETRY_COUNT=0
      
      :RETRY
      move /Y "${filePath}\\GWlauncher-new.exe" "${filePath}\\GWlauncher.exe"
      if errorlevel 1 (
          set /A RETRY_COUNT+=1
          if %RETRY_COUNT% lss %MAX_RETRIES% (
              timeout /t 1 /nobreak >nul
              goto RETRY
          ) else (
              echo Maximum retries reached. Exiting.
              exit /b 1
          )
      )
      start "" "${filePath}\\GWlauncher.exe"
      del /F "${filePath}\\launcher-update.bat"
      `;

      fs.writeFileSync(`${filePath}\\launcher-update.bat`, batchContent, 'utf8');

      const { spawn } = require("child_process");
      spawn(`start /min cmd.exe /C ${filePath}\\launcher-update.bat`, {
        detached: true,
        shell: true,
        cwd: filePath,
      });

      ipcRenderer.send("close-app");
    };`

**Comment by gustavokei** [comment]
Hello, appreciate the follow up.

Make sure to replace all occurrences of "launcher.exe" and "launcher-new.exe". Or rename your "GWlauncher.exe" to just "launcher.exe" as I've suggested before.
After the changes, is the auto update process working?

**Comment by antotor** [comment]
I compleatly rename gwlauncher to launcher in all code parts, but have same error:
![image](https://github.com/gustavokei/electron-game-updater/assets/5446923/83a67721-28a0-450f-aa12-7d5f62f9f246)

**Comment by antotor** [comment]
I think, problem in this part of code: 
![image](https://github.com/gustavokei/electron-game-updater/assets/5446923/1d17ffa1-4dfc-44d8-b4c6-752d58f10caf)
After change close-app comand on commented part - i cant see error. But launcher windows cant close compleatly and .bat file cant start.

**Comment by gustavokei** [comment]
Hi, I was able to reproduce your issue and made a quick workaround. Please, either pull the [changes](https://github.com/gustavokei/electron-game-updater/commit/31ac201e9ba168d5e13b22c59f37c1e216d7c951) or implement them in your project and see if it worked.

**Comment by antotor** [comment]
If i manualy close old launcher and manualy start .bat file - files overwrite work correctly.

**Comment by gustavokei** [comment]
Thanks for the feedback!
I have pushed [another commit](https://github.com/gustavokei/electron-game-updater/commit/f74179fcf17d50830d3bdb27f07f4a33ece3863b), can you test it again?

**Comment by gustavokei** [comment]
That's great!
Thank you, too, for bringing the issue up.
Should you encounter any other challenges, don't hesitate to open another issue here.
