### ISSUE TITLE
Problem with new launcher version detect.

### ISSUE THREAD

**Issue by antotor** [gustavokei/electron-game-updater#5]
Hello again!

I found another problem with use launcher. Sometimes, after build and upload new version of launcher - and start local launcher old version, launcher cant see new version. For example, i develop and build version 0,37. I start launcher with version 0,36. Launcher 0,36 cant see new version.

If i clean application cash (C:\Users\%USER%\AppData\Roaming\Launcher - launcher download update correctly. Maybe clean cash automaticaly after start launcher?

**Comment by gustavokei** [comment]
Hello!

For autoupdate, please refer to the `egu-config.json` configuration, as already mentioned in the readme:
```json
{
  "launcherVer": 1, // this must be a number and will be used to auto update your portable .exe if there is a higher version on "configFileRemote" field
  "launcherUrl": "https://url-to-your/launcher.exe", // updater will download and autoupdate if remote launcherVer is higher than local
  "configFileRemote": "https://url-to-your/egu-config.json", // remote url for egu-config.json (the updater will compare the launcherVer field)
}
```
Make sure to use integer numbers in the `launcherVer` field. For instance, 1, 2, 3, 4, etc. (It doesn't necessarily have to correspond to the actual launcher version).

It should autoupdate when your local `egu-config.json` has a lower version than the remote one.

**Comment by antotor** [comment]
I am sory for inaccurate description of problem. I use integer numbers vor version (currently - 37). But i draw 0.VERSION on frontend.

Updated work correcly 9 from 10 versions. But sometimes, launcher not see changes in egu-config.json on the servers. Clean launcher cash in folder (/AppData/...) - solves this problem for next 5-9 updates.

**Comment by gustavokei** [comment]
Thanks for clarifying! I think I understand now.

I have implemented a workaround to bust cache on every request, make sure to update your project with the [new changes](https://github.com/gustavokei/electron-game-updater/commit/20d0a35dca7afd1acc8090be9d120cbeb7772c7a).
However, if your files are cached on the server, you will have to make changes on your side.

**Comment by antotor** [comment]
Thank you!

**Comment by gustavokei** [comment]
You're welcome! Thanks again for pointing out another problem within the project.

Should you come across another one, feel free to open another issue.
